name: Test

on:

  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fix Gradle Corruption
        run: |
          cd /usr/local/lib/android/sdk/build-tools/31.0.0 \
          && mv d8 dx \
          && cd lib \
          && mv d8.jar dx.jar

      - name: Installing Fastlane Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Running Fastlane
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'generateReleaseBuild'
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: app/build/outputs/apk/release/*

