name: Test

on:

  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fix Gradle Corruption
        run: |
          cd /usr/local/lib/android/sdk/build-tools/31.0.0 \
          && mv d8 dx \
          && cd lib \
          && mv d8.jar dx.jar

      - name: Build with Gradle
        run: ./gradlew build

#    - name: Installing Fastlane Dependencies
#      uses: ruby/setup-ruby@v1
#      with:
#        ruby-version: 2.7.2
#
#    - name: Running Fastlane
#      uses: maierj/fastlane-action@v2.0.1
#      with:
#         lane: 'test'